### ISSUE TITLE
Chromedriver Version

### ISSUE THREAD

**Issue by raisa2010** [gristlabs/mocha-webdriver#41]
Hello!

I was trying to run this with grist-core but the yarn install fails on Mac with M1 chips due to chromedriver 74.0.0 with the following error message. However, if i manually change the yarnpkg to use version 98.0.0, it can install properly. I was wondering if there is any potential change in the pipeline to update the chromedriver version for this library or whether there may be some unforeseen consequences?

<img width="1179" alt="Screenshot 2023-02-25 at 4 50 20 PM" src="https://user-images.githubusercontent.com/18502799/221348090-f1d1a8d8-5bdd-41c6-9028-dbb13b86c1fd.png">

Older chromedriver version installs seem to be failing due to significantly old node version requirements (0.8.x)

Thank you!

**Comment by dsagal** [comment]
I don't know of any issue with upgrading chromedriver to latest (latest might be 110.0.0, right?) No objection to doing that.

As for [grist-core](https://github.com/gristlabs/grist-core), as far as I know there are quite a few other changes or updates that need to happen for it to work with newer node on Macs with M1 chips. Until those are ready, grist-core works with node 14 when Rosetta is installed on the Mac. And in that case, mocha-webdriver works too, even with the current out-of-date chromedriver dependency.

**Comment by raisa2010** [comment]
got it, thank you!
